name: Lint Code

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Ruff check
        uses: astral-sh/ruff-action@v4.0.0
        with:
          args: check --fix

      - name: Run Ruff format
        uses: astral-sh/ruff-action@v4.0.0
        with:
          args: format

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install JSHint
        run: npm install -g jshint

      - name: Run JSHint
        run: find ./server/database -name "*.js" -exec jshint {} +
